.gitignore
.idea/externalDependencies.xml

Configure editorconfig

---

.github/requirements.txt
.github/workflows/pr-title-format.yml

feat(ci): add PR title format validator

---

.github/actions/setup-gradle-properties/action.yml
.github/gradle.properties

And provide a basic `gradle.properties` file for CI builds.

feat(ci): create local composite action to use custom `gradle.properties`

---

.gitattributes

feat(git): prepare LFS support for snapshots testing

---

.github/workflows/pr.yml
gradle/libs.versions.toml
spark/build.gradle.kts
spark/dependencies/releaseRuntimeClasspath.txt

feat: add dependencyGuard plugin and configure `releaseRuntimeClasspath`

---

gradle.properties
spark/build.gradle.kts
spark/src/main/kotlin/com/adevinta/spark/Spark.kt

- `publishToMavenLocal` -> `~/.m2/`
- `publishMavenPublicationToLocalRepository` -> `./build/.m2/`

feat(publishing): configure publication of the main library with javadoc

---

spark/build.gradle.kts

feat: enable `allWarningsAsErrors`

---

.github/workflows/pr.yml
spark/build.gradle.kts
spark/src/main/kotlin/com/adevinta/spark/Spark.kt

feat: archive and upload Lint SARIF report

---

.github/actions/diffuse-aar/action.yml
.github/workflows/pr.yml

feat: diffuse aar

---

spark/build.gradle.kts
spark/src/main/kotlin/com/adevinta/spark/Spark.kt
spark/src/test/kotlin/com/adevinta/spark/SparkTest.kt

Must be configured with `freeCompilerArgs`...

feat: enable explicitApi for Android module

---

.github/workflows/pr.yml

otherwise the step is completely ignored, not even evaluated...

fix(workflow): adding `always()` as part of the condition

---

.github/actions/archive-lint-reports/action.yml
.github/workflows/pr.yml

And use the project root directory to upload all SARIF reports.

feat(workflow): merge SARIF analysis inside the composite action

---

sample/src/main/kotlin/com/adevinta/spark/sample/MainActivity.kt
spark/build.gradle.kts

feat: publish `spark-lint` from the `spark` module

---

.github/workflows/dokka.yml
gradle/libs.versions.toml
spark/build.gradle.kts

feat: publish Dokka to GitHub Pages

---

spark/src/main/kotlin/com/adevinta/spark/component/spacer/Spacers.kt

Just copy and improved a bit our LBC implementation of the Spacer Foundation Composable
This component is "required" to start importing the toggles and others components and is part of #
No screenshot since as this Composable doesn't draw anything
Related to #1

feat: Add Spacers Composable

---

.github/actions/archive-paparazzi-reports/action.yml
.github/actions/paparazzi-report/action.yml
.github/workflows/ci.yml

feat: paparazzi tests and reports

---

.github/actions/paparazzi-report/action.yml

And add a `work in progress` flag.

chore: update bot username

---

spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_badge_badge_dark.png
spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_badge_badge_light.png
spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_badge_badgedbox_dark.png
spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_badge_badgedbox_light.png
spark/src/main/kotlin/com/adevinta/spark/components/badge/Badge.kt
spark/src/main/kotlin/com/adevinta/spark/components/badge/BadgedBox.kt

Add Badge components
Close #174

chore: Add Badge components

---

spark/src/main/kotlin/com/adevinta/spark/components/surface/Surface.kt

Add Surface components
close #177

chore: Add Surface components

---

spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_cards_card_dark.png
spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_cards_card_light.png
spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_cards_elevatedcard_dark.png
spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_cards_elevatedcard_light.png
spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_cards_outlinedcard_dark.png
spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_cards_outlinedcard_light.png
spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_defaultgroup_card_dark.png
spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_defaultgroup_card_light.png
spark/src/main/kotlin/com/adevinta/spark/components/card/Card.kt
spark/src/main/kotlin/com/adevinta/spark/components/card/CardDefaults.kt
spark/src/main/kotlin/com/adevinta/spark/components/card/ElevatedCard.kt
spark/src/main/kotlin/com/adevinta/spark/components/card/OutlinedCard.kt

Add Card components
Close #176

chore: Add Card components

---

spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_separator_divider_dark.png
spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_separator_divider_light.png
spark/src/main/kotlin/com/adevinta/spark/components/divider/Divider.kt

Add Divider components
Close #180

chore: Add Divider components

---

.github/CODEOWNERS

Marina is part of the maintainer and should be added to the code owner so that its review allow merges

chore: Add Marina Romanova as code owner

---

CHANGELOG.md
gradle.properties

chore: prepare version 0.0.3

---

CHANGELOG.md
gradle.properties

We need #345 Before merging this.

chore: prepare version 0.1.0

---

.github/actions/dependencyguard-baseline/action.yml
.github/workflows/chat-bot-commands.yml

Add a chat-bot command to trigger `gradlew dependencyGuardBaseline`

ci(bot): add DependencyGuardBaseline trigger

---

spark-icons/src/main/kotlin/com/adevinta/spark/icons/SparkIcon.kt
spark-icons/src/main/res-iconography/categories/drawable/spark_icons_family.xml

Add a missing icon Categories/Family 
Icon requested by a feature team
close #383

fix: Add Categories/Family Icon

---

.github/workflows/ci.yml
build-logic/src/main/kotlin/com/adevinta/spark/SparkAndroidApplicationPlugin.kt

ci: archive APKs for each CI build

---

scripts/svg2avd/COPYRIGHT.xml
scripts/svg2avd/svg2avd.main.kts

#393
We need to automate icons updates.
The current source of truth is https://github.com/adevinta/spark-tokens/ (SVG files).
Example usage:
```bash
./svg2avd.main.kts --input="in" --output="out" --prefix="spark_icons_" --copyright="COPYRIGHT.xml"
```

ci: create `svg2avd.main.kts` Kotlin script

---

.github/workflows/pr-icon-updates.yml

ci: create `pr-icon-updates.yml`

---

spark/src/main/kotlin/com/adevinta/spark/components/badge/Badge.md
spark/src/main/kotlin/com/adevinta/spark/components/buttons/Buttons.md
spark/src/main/kotlin/com/adevinta/spark/components/chips/Chip.md
spark/src/main/kotlin/com/adevinta/spark/components/icons/Icon.md
spark/src/main/kotlin/com/adevinta/spark/components/progress/Spinner.md
spark/src/main/kotlin/com/adevinta/spark/components/toggles/CheckBox.md
spark/src/main/kotlin/com/adevinta/spark/components/toggles/RadioButton.md
spark/src/main/kotlin/com/adevinta/spark/components/toggles/Switch.md

Some tables were not formatted and the header were not clear in the package view

docs: Fix the layout of dokka package doc

---

spark/src/main/kotlin/com/adevinta/spark/components/tags/Tag.md

Add documentation for the tag component
The documentation for the tag was missing (sorry 🙈) so we need to add it as it was available for long time now.
Close #414

docs: Add Tag documentation

---

catalog/src/main/kotlin/com/adevinta/spark/catalog/themes/SegmentedButton.kt
catalog/src/main/kotlin/com/adevinta/spark/catalog/themes/ThemePicker.kt
catalog/src/main/kotlin/com/adevinta/spark/catalog/util/Previews.kt
spark/src/main/kotlin/com/adevinta/spark/components/badge/BadgeStyle.kt
spark/src/main/kotlin/com/adevinta/spark/components/buttons/Button.kt
spark/src/main/kotlin/com/adevinta/spark/components/chips/ChipStyles.kt
spark/src/main/kotlin/com/adevinta/spark/components/navigation/NavigationRailItem.kt
spark/src/main/kotlin/com/adevinta/spark/components/rating/RatingLong.kt
spark/src/main/kotlin/com/adevinta/spark/components/snackbars/Snackbar.kt
spark/src/main/kotlin/com/adevinta/spark/components/tab/LeadingIconTab.kt
spark/src/main/kotlin/com/adevinta/spark/components/tags/Tag.kt
spark/src/main/kotlin/com/adevinta/spark/components/textfields/DefaultSparkTextFieldColors.kt
spark/src/main/kotlin/com/adevinta/spark/components/toggles/SwitchDefaults.kt
spark/src/main/kotlin/com/adevinta/spark/tokens/Color.kt
spark/src/main/kotlin/com/adevinta/spark/tokens/ContentColor.kt
spark/src/main/kotlin/com/adevinta/spark/tokens/Type.kt

feat: Add extensions for applying dim to colors and weight to typos

---

CHANGELOG.md
gradle.properties

chore: prepare version 0.3.0

---

catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/checkboxes/CheckboxConfigurator.kt
catalog/src/main/kotlin/com/adevinta/spark/catalog/examples/samples/checkbox/CheckboxExamples.kt
catalog/src/main/res/values/strings.xml
spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_toggles_checkbox_dark.png
spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_toggles_checkbox_light.png
spark/src/main/kotlin/com/adevinta/spark/components/toggles/CheckBox.kt
spark/src/main/kotlin/com/adevinta/spark/components/toggles/CheckBox.md
spark/src/main/kotlin/com/adevinta/spark/components/toggles/ToggleIntent.kt

Add intents to `CheckBox` and `CheckboxLabelled`
Present in the current PR
- We still cannot have desired color for disabled state due to [issue](https://issuetracker.google.com/issues/291943198)
- We still need to handle error state
close #301

feat: Add Intents to checkbox

---

spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_toggles_labelledslot.png
spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_toggles_radiobutton_dark.png
spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_toggles_radiobutton_light.png
spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_toggles_radiobuttonlabelled_dark.png
spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_toggles_radiobuttonlabelled_light.png
spark/src/main/kotlin/com/adevinta/spark/components/toggles/CheckBox.md
spark/src/main/kotlin/com/adevinta/spark/components/toggles/RadioButton.kt
spark/src/main/kotlin/com/adevinta/spark/components/toggles/RadioButton.md
spark/src/main/kotlin/com/adevinta/spark/components/toggles/ToggleIntent.kt

- Add missing ToggleIntents support to radio button component.
- Update colors as per specs
Present in the current PR
close #568

feat: Add all color intents to RadioButton

---

spark/src/main/kotlin/com/adevinta/spark/tokens/Color.kt

Update color value for `onAccentVariant`
related to #578

fix: Update color value for onAccentVariant

---

.github/CODEOWNERS
catalog/src/main/res/values/strings.xml

[Contributing](https://github.com/adevinta/spark-android/blob/main/docs/contributing.md) has more information and tips for a great pull request.

docs: add my name to code owners

---

CHANGELOG.md
gradle.properties

chore: prepare version 0.4.0

---

CHANGELOG.md
gradle.properties

Upgrade from 0.3.1 to 0.4.1
We skip the 0.4.0 as I made a mistake when releasing the 0.4.0

chore: prepare version 0.4.1

---

gradle.properties

Bump version to `0.5.0-SNAPSHOT`

chore: prepare next development version

---

catalog/src/main/res/values/strings.xml

fix: catalog app name

---

catalog/src/main/kotlin/com/adevinta/spark/catalog/icons/IconsScreen.kt

We have 400+ icons at the moment to avoid freezing UI get all icons in couroutines.

chore: Fetch icon resources in coroutines in CatalogApp

---

catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/buttons/IconButtonsConfigurator.kt
catalog/src/main/kotlin/com/adevinta/spark/catalog/examples/samples/buttons/IconButtonsExamples.kt
spark/src/main/kotlin/com/adevinta/spark/components/iconbuttons/IconButton.kt
spark/src/main/kotlin/com/adevinta/spark/components/iconbuttons/IconButtonContrast.kt
spark/src/main/kotlin/com/adevinta/spark/components/iconbuttons/IconButtonFilled.kt
spark/src/main/kotlin/com/adevinta/spark/components/iconbuttons/IconButtonGhost.kt
spark/src/main/kotlin/com/adevinta/spark/components/iconbuttons/IconButtonOutlined.kt
spark/src/main/kotlin/com/adevinta/spark/components/iconbuttons/IconButtonTinted.kt

- Add loading state to `IconButton` 
- Update configurable example
close #654

feat: Add loading state to the IconButton component

---

RELEASING.md

It seems like GitHub does not like to receive this kind of push commands...

fix(docs): Replace onliner with two distinct commands

---

.run/♻️ clean.run.xml
.run/⚡️ Run unit tests & screenshot tests.run.xml
.run/✨ spotlessApply.run.xml
.run/💂 dependencyGuardBaseline.run.xml
.run/📦 Publish to MavenLocal.run.xml
.run/📸 Record Paparazzi Golden Images.run.xml

feat(intellij): create main run configurations

---

.github/actions/spotless-apply/action.yml
.github/workflows/chat-bot-commands.yml

Adds a new `@spark-ui-bot spotless` chat bot command to run spotless on CI.

feat: add spotless chat-bot command

---

.github/actions/spotless-apply/action.yml

https://github.com/adevinta/spark-android/actions/runs/6431073478/job/17463238819#step:6:380

fix: typo in `git commit` command

---

build-logic/build.gradle.kts
settings.gradle.kts

https://blog.gradle.org/simpler-kotlin-dsl-property-assignment

chore(gradle): Simpler Kotlin DSL Property Assignment

---

catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/rating/RatingConfigurator.kt
catalog/src/main/kotlin/com/adevinta/spark/catalog/examples/samples/rating/RatingExamples.kt
catalog/src/main/kotlin/com/adevinta/spark/catalog/model/Components.kt
catalog/src/main/res/values/strings.xml
catalog/src/main/res/values/themes.xml
spark/src/main/kotlin/com/adevinta/spark/components/rating/RatingDisplay.kt
spark/src/main/kotlin/com/adevinta/spark/components/rating/RatingLong.kt
spark/src/main/kotlin/com/adevinta/spark/components/rating/RatingSmall.kt
spark/src/main/kotlin/com/adevinta/spark/components/rating/RatingStar.kt

Add examples for all type of ratings (Spark & Polaris) and a configurator for Rating display values and sizes
Close #817 
Close #818

chore: Add examples ad configurator for Rating Display

---

CHANGELOG.md
gradle.properties

Upgrade the version from 0.5.0 to 0.6.0

chore: prepare version 0.6.0

---

catalog/src/main/res/values/themes.xml
gradle.properties
spark/src/main/kotlin/com/adevinta/spark/components/dialog/ModalScaffold.kt

- Fix the content padding not being passed to it's children.
- Invert the position of buttons.
- Inset for non edge to edge app was broken and displaying the content bellow the system bars.
- Add the support for WindowHeightSizeClass.Expanded to show the fullscreen modal in portrait
Closes #861

chore: hotfix 0.6.1 - Fix Modal reported issues

---

.github/workflows/firebase-app-distribution.yml

feat(app-distribution): Allow `groups` as workflow input

---

.github/workflows/firebase-app-distribution.yml

In non-`workflow_dispatch`, `inputs` are not provided.

fix(app-distribution): ensure default value

---

catalog/src/main/kotlin/com/adevinta/spark/catalog/examples/samples/text/TextLinkExamples.kt
spark/src/main/kotlin/com/adevinta/spark/components/text/TextLink.kt

feat: Add variant TextLinkButton

---

.github/dependabot.yaml

- https://github.com/dependabot/dependabot-core/issues/2178

chore(dependabot): explicit paths for composite actions

---

.github/workflows/gradle-wrapper-updater.yml

See failure: https://github.com/adevinta/spark-android/actions/runs/7704203436/job/20996062150#step:3:107
Also, see https://github.com/gradle-update/update-gradle-wrapper-action/issues/732#issuecomment-1916609792 for the warning regarding "Unexpected input `pr-title-template`".

fix(action): setup Java & Gradle in `gradle-wrapper-updater.yml`

---

.github/workflows/gradle-wrapper-updater.yml

Android Studio does not like this property...

fix(gradle): disable `set-distribution-checksum`

---

.github/actions/setup-java/action.yml
build-logic/src/main/kotlin/com/adevinta/spark/SparkDokkaPlugin.kt

chore: bump to Java 21 on CI

---

CHANGELOG.md
gradle.properties

Update changelog and spark version to stable

chore: prepare version 0.7.0

---

catalog/src/main/kotlin/com/adevinta/spark/catalog/examples/samples/tokens/colors/ColorSample.kt

fix: type erasure of value class inlined in release builds

---

.gitignore

https://kotlinlang.org/docs/whatsnew-eap.html#new-directory-for-kotlin-data-in-gradle-projects

chore(gitignore): add `.kotlin` for Kotlin 2

---

spark/src/main/kotlin/com/adevinta/spark/components/progress/tracker/ProgressSizes.kt
spark/src/main/kotlin/com/adevinta/spark/components/progress/tracker/ProgressTracker.kt
spark/src/main/kotlin/com/adevinta/spark/components/progress/tracker/ProgressTrackerMeasurePolicy.kt

Add Large, Medium, Small
Progress of #780

feat(progresstracker): Add sizes

---

catalog/src/main/kotlin/com/adevinta/spark/catalog/backdrop/Backdrop.kt
catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/progresstracker/ProgressTrackerConfigurator.kt
catalog/src/main/kotlin/com/adevinta/spark/catalog/model/Components.kt
catalog/src/main/kotlin/com/adevinta/spark/catalog/themes/SegmentedButton.kt
catalog/src/main/res/values/strings.xml
spark/src/main/kotlin/com/adevinta/spark/components/card/CardDefaults.kt
spark/src/main/kotlin/com/adevinta/spark/components/progress/tracker/ProgressTracker.kt
spark/src/main/kotlin/com/adevinta/spark/components/progress/tracker/ProgressTrackerIntent.kt
spark/src/main/kotlin/com/adevinta/spark/components/progress/tracker/StepAnimation.kt

feat(progresstracker): Add configurator

---

.github/actions/diffuse-aar/action.yml

https://github.com/JakeWharton/diffuse/releases/tag/0.3.0

chore(diffuse): Bump default version 0.3.0

---

CHANGELOG.md
gradle.properties

Update changelog and spark version to stable

chore: prepare version 0.8.0

---

catalog/src/main/res/values/strings.xml

fix: Update strings.xml that had a unused res

---

catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/component/Component.kt
catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/text/TextLinkConfigurator.kt
catalog/src/main/kotlin/com/adevinta/spark/catalog/model/Configurator.kt

The textlink configurator was using a scaffold while inside a scrollable
column which is not supported as the height is infinite.
Close #1021

fix(configurator): fix textlink configurator

---

.github/actions/paparazzi-golden-images/action.yml
.github/workflows/paparazzi-golden-images.yml

This should allow us to manually trigger a full regeneration of Paparazzi golden images.

feat: add Paparazzi as a manual workflow

---

.github/actions/paparazzi-golden-images/action.yml

https://github.com/adevinta/spark-android/actions/runs/8572748056/job/23495995480#step:3:5667

fix(workflow): add missing github token for `gh`

---

.github/workflows/ci.yml
lava.yaml

https://github.com/adevinta/lava

feat: run Lava Vulnerability Scanner on CI workflow

---

catalog/src/main/res/values/strings.xml
spark/src/main/res/values-de/strings.xml
spark/src/main/res/values-fr/strings.xml
spark/src/main/res/values/strings.xml

Add translated strings from en to de
Close #958

feat(locale): Add de locale for spark a11y strings

---

CHANGELOG.md
gradle.properties

chore: prepare version 0.9.0

---

.github/actions/paparazzi-golden-images/action.yml
.github/actions/paparazzi-report/action.yml
.github/workflows/paparazzi-golden-images.yml
.run/📸 Record Paparazzi Golden Images.run.xml
docs/CONTRIBUTING.md

Replace globbing with proper git pathspec.

feat(paparazzi): update composite actions and update Gradle task references

---

catalog/src/main/kotlin/com/adevinta/spark/catalog/examples/samples/progresstracker/ProgressTrackerExamples.kt

Fix a bug during test session mentioned in this ticket #1027

fix: ProgressTracker Examples crash

---

catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/textfields/ComboBoxConfigurator.kt
catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/textfields/DropdownsConfigurator.kt
catalog/src/main/kotlin/com/adevinta/spark/catalog/model/Components.kt
catalog/src/main/res/values/strings.xml
spark/src/main/kotlin/com/adevinta/spark/components/bottomsheet/BottomSheet.kt
spark/src/main/kotlin/com/adevinta/spark/components/menu/DropdownMenu.kt

Fork the impl of the DropDown item to simplify the application of Spark specs on the item like the spacings, default text styles, dimensions...
Closes #1145

feat(dropdown): Apply Spark style to the Dropdown Item

---

catalog/src/main/kotlin/com/adevinta/spark/catalog/examples/samples/text/DropdownExamples.kt
spark/src/main/kotlin/com/adevinta/spark/components/textfields/Dropdown.kt

Add multi selection example
Also add the missing padding in the dropdown menu
Closes #1162

feat(dropdown): Add multi selection example

---

catalog/src/main/kotlin/com/adevinta/spark/catalog/examples/samples/buttons/ButtonsExamples.kt

Button - toggle feature
Closes [#945](https://github.com/adevinta/spark-android/issues/945)

feat(Button): Add button toggle example

---

catalog/src/main/kotlin/com/adevinta/spark/catalog/model/Components.kt

fix: Catalog app examples crash 

---

CHANGELOG.md
catalog/src/main/kotlin/com/adevinta/spark/catalog/examples/samples/dialog/ModalExamples.kt
catalog/src/main/kotlin/com/adevinta/spark/catalog/examples/samples/dialog/modal/ModalSample.kt
spark/src/main/kotlin/com/adevinta/spark/components/dialog/ModalScaffold.kt
spark/src/main/res/values-de/strings.xml
spark/src/main/res/values-fr/strings.xml
spark/src/main/res/values/strings.xml

fix(modal): Allow ModalScaffold to take no buttons (#1172)

---

CHANGELOG.md
gradle.properties

chore: prepare version 0.11.0

---

gradle/libs.versions.toml

fix(kotlin): specify Kotlin BoM version

---

catalog/src/main/kotlin/com/adevinta/spark/catalog/CatalogApp.kt
catalog/src/main/kotlin/com/adevinta/spark/catalog/ui/Backdrop.kt

It'll serve as a module for all common components used in the catalog app

refactor(backdrop): Rename backdrop module to ui

---

catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/modal/ModalConfigurator.kt
catalog/src/main/kotlin/com/adevinta/spark/catalog/model/Components.kt
catalog/src/main/kotlin/com/adevinta/spark/catalog/ui/shaders/colorblindness/ColorBlindSettings.kt

Add Modal configurator and exlude the colorblindness severity slider from back gestures

feat: Add missing Modal configurator

---

catalog/src/main/kotlin/com/adevinta/spark/catalog/icons/IconsScreen.kt

| Before | Diff | After |
|--------|--------|--------|
| ![before](https://github.com/user-attachments/assets/a91328d4-b8e5-4339-8412-e28119d9bbd7) | ![diff](https://github.com/user-attachments/assets/041974e8-d148-4dda-b6a5-458d3acc27ed) | ![after](https://github.com/user-attachments/assets/2e471ab7-b165-4dbd-b3b5-849360f17262) |

fix(catalog): clipping issue on IconsScreen.kt

---

spark/src/main/kotlin/com/adevinta/spark/components/dialog/ModalScaffold.kt

Add a new `inEdgetoEdge` argument to explecitly tell the component in which support it is.
Refactor Modal Scaffold to better support cases with and without edge to edge support while lbc is migrating their screens

fix: adjust api & impl of ModalScaffold to better handle both screens w & w/ edge to edge

---

catalog/src/main/AndroidManifest.xml
catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/ComponentsScreen.kt
catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/Navigation.kt
catalog/src/main/kotlin/com/adevinta/spark/catalog/examples/ComponentsScreen.kt
catalog/src/main/kotlin/com/adevinta/spark/catalog/examples/Navigation.kt
catalog/src/main/kotlin/com/adevinta/spark/catalog/icons/IconDemoScreen.kt
catalog/src/main/kotlin/com/adevinta/spark/catalog/icons/IconsScreen.kt
catalog/src/main/kotlin/com/adevinta/spark/catalog/icons/Navigation.kt

Replace all the string routes by typed ones.
Encapsulate the navigation to be only accesible from specific destinations/graphs

refactor: Use the new Typesafe routes for navigation

---

catalog/src/main/kotlin/com/adevinta/spark/catalog/examples/samples/tokens/TokensExamples.kt
catalog/src/main/kotlin/com/adevinta/spark/catalog/examples/samples/tokens/shapes/ShapeCustomSample.kt
catalog/src/main/kotlin/com/adevinta/spark/catalog/examples/samples/tokens/shapes/ShapeSample.kt
spark/src/main/kotlin/com/adevinta/spark/tokens/Order.kt
spark/src/main/kotlin/com/adevinta/spark/tokens/Shape.kt

Add a couple of showcases for the Shapes token
Part of #1177 
| Menu | Showcase1 | Showcase2 |
| ------------- | ------------- | ------------- |
| <img src="https://github.com/user-attachments/assets/ac5bc853-7987-4a3b-a24f-2f5fa6298b83" width="200"/> | <img src="https://github.com/user-attachments/assets/7d41196a-10e5-4beb-aac1-2c29790266ab" width="200"/> | <img src="https://github.com/user-attachments/assets/38d5c470-104c-440a-a81a-40ba0ad4fc73" width="200"/> |

feat: add Shapes showcases

---

.github/workflows/auto-author-assign.yml

https://github.com/adevinta/spark-android/actions/runs/12770188857/job/35594444314

chore(gha): add missing `pull-requests` permission

---

catalog/src/main/kotlin/com/adevinta/spark/catalog/examples/samples/icons/IconsExamples.kt

https://github.com/adevinta/spark-android/security/code-scanning/601

fix: auto-boxing in `IconsExamples.kt`

---

catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/image/ImageConfigurator.kt
gradle/libs.versions.toml
spark/build.gradle.kts
spark/src/main/kotlin/com/adevinta/spark/components/image/Image.kt
spark/src/main/kotlin/com/adevinta/spark/components/image/UserAvatar.kt

Close [SPA-492](https://jira.ets.mpi-internal.com/browse/SPA-492)

fix: Image using Subcomposition

---

catalog/src/main/kotlin/com/adevinta/spark/catalog/examples/samples/dialog/modal/ModalSample.kt
spark/src/main/kotlin/com/adevinta/spark/components/dialog/ModalScaffold.kt

(cherry picked from commit 32c98720393a8ab1c25e03ebfbc2e35f3ffa2e40)
See fix here #1450

refactor(modal): edge-to-edge setup now optin instead of optout (#1450)

---

build-logic/build.gradle.kts
build-logic/src/main/kotlin/com/adevinta/spark/SparkProperties.kt
build-logic/src/main/kotlin/com/adevinta/spark/SparkSpotlessPlugin.kt
gradle/libs.versions.toml
spark/build.gradle.kts
spark/dependencies/releaseRuntimeClasspath.txt

- delete unused entries
- inline versions if they are only used once
- add missing BoM for Coil
- space unrelated entries
- some minor renames to respect conventions

chore: cleanup Gradle Version Catalog

---

spark/lint.xml
spark/src/main/kotlin/com/adevinta/spark/SparkTheme.kt
spark/src/main/kotlin/com/adevinta/spark/tools/SparkExceptionHandler.kt

Rename `SparkLogger` to `SparkExceptionHandler`
`SparkExceptionHandler` better reflect its purpose of handling exceptions within Spark

refactor: Rename SparkLogger to SparkExceptionHandler

---

.github/workflows/gradle-wrapper-updater.yml

https://github.com/leboncoin/spark-android/actions/runs/14671203632/job/41177913411
```
Creating Pull Request
Error: ❌ Resource not accessible by personal access token - https://docs.github.com/rest/pulls/pulls#create-a-pull-request
```

chore: add missing permissions for `gradle-wrapper-updater.yml`

---

spark/lint.xml
spark/src/main/kotlin/com/adevinta/spark/SparkTheme.kt
spark/src/main/kotlin/com/adevinta/spark/components/image/Image.kt
spark/src/main/kotlin/com/adevinta/spark/tools/logger/SparkLogger.kt

Image component will no longer crash when no size is defined on it.
We now have a way to signal if a Image component has not size defined and the behavior of this signal can be change by the consumer

fix(image): image should no longer crash when no size is defined

---

spark-lint/src/test/kotlin/com/adevinta/spark/lint/MaterialComposableUsageDetectorTest.kt
spark-lint/src/test/kotlin/com/adevinta/spark/lint/StringResourceAnnotationDetectorTest.kt
spark-lint/src/test/kotlin/com/adevinta/spark/lint/stubs/ComposableStub.kt
spark-lint/src/test/kotlin/com/adevinta/spark/lint/stubs/SparkComponentsStub.kt
spark-lint/src/test/kotlin/com/adevinta/spark/lint/stubs/SparkComponentsStubs.kt

Split the spark stub into multiples files
This should make the test more reliable since now we verify the spart stub components with correct packages names

 fix(lint): fix stubs used for lint rule testing

---

.github/workflows/ci.yml

This parallelisation reduces the overall build time by half.
<details><summary>on main branch (with invalidated cache)</summary>
<p>
</p>
</details> 
<details><summary>on main branch (with 100% cache hit)</summary>
<p>
</p>
</details> 
<details><summary>on PR branch (without populated cache)</summary>
<p>
</p>
</details>
<details><summary>on PR branch (with build cache)</summary>
<p>
</p>
</details>

feat(ci): optimize CI workflow by splitting jobs

---

.github/workflows/ci.yml

feat(ci): add custom job to simplify the required status check

---

gradle.properties

Bump to publish fixes from #1596 and #1597

chore: Bump version to 1.3.0-alpha05

---

gradle.properties

#1611 should allow us to publish all artifacts again

feat: Bump version to 1.3.0-alpha08

---

RELEASING.md

Follow up from https://github.com/leboncoin/spark-android/pull/1612

fix(documentation): Remove OSSRH part from PUBLISHING.md

---

catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/toggles/CheckboxConfigurator.kt
catalog/src/main/kotlin/com/adevinta/spark/catalog/examples/samples/toggles/CheckboxExamples.kt
spark-screenshot-testing/src/test/kotlin/com/adevinta/spark/toggles/CheckboxScreenshot.kt
spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.toggles_CheckboxScreenshot_all_states_dark.png
spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.toggles_CheckboxScreenshot_all_states_light.png
spark/src/main/kotlin/com/adevinta/spark/components/toggles/CheckBox.kt
spark/src/main/kotlin/com/adevinta/spark/components/toggles/CheckBox.md
spark/src/main/kotlin/com/adevinta/spark/components/toggles/ToggleIntent.kt

- Add overloads for the new api & deprecated the previous one.
- Remove the legacy intents and content side api from the screenshot tests, examples and configurator.
Close [LBCSPARK-277](https://jira.ets.mpi-internal.com/browse/LBCSPARK-277)

feat(checkbox): Remove intents and content side to align with new specs

---

build-logic/build.gradle.kts
build-logic/src/main/kotlin/com/adevinta/spark/SparkPublication.kt
gradle/libs.versions.toml

https://developer.android.com/build/releases/gradle-plugin-roadmap

chore: migrate to `com.android.tools.build:gradle-api`
