leboncoin/spark-android

- .github/actions/archive-junit-reports/action.yml
- .github/actions/archive-lint-reports/action.yml
This is already handled by `actions/upload-artifact@v3`, and providing a `.zip` extension will lead to a `.zip` in the un-zipped file.
> fix: remove zip extension from archive name

- CODE_OF_CONDUCT.md
Close #21 
This is shared [with the web](https://github.com/adevinta/spark/tree/main/documentation/contributing/code-of-conduct)
> docs: Add code of conduct to the projct

- .github/workflows/ci.yml
- .github/workflows/dokka.yml
- .github/workflows/gradle.yml
To reduce the total cache upload.
> chore: add `gradle-home-cache-cleanup: true` to first invocation of `gradle/gradle-build-action`

- build-logic/src/main/kotlin/com/adevinta/spark/SparkAndroidComposePlugin.kt
- spark/build.gradle.kts
Remove ExperimentalSparkApi & InternalSparkApi from plugin compiler args to move them on modules that use them
We get a warning when adding them on modules that don't use them which makes the build fail as we consider warnings as errors
> fix: Remove ExperimentalSparkApi & InternalSparkApi from plugin compiler args

- spark/src/main/kotlin/com/adevinta/spark/components/rating/RatingStar.kt
- spark/src/main/kotlin/com/adevinta/spark/tokens/PaletteTokens.kt
Change Surfer90 color from `#7B7986` to `#EBEBED`
`#7B7986` is the color to Surfer50 and was wrongly used here
<table>
<tr>
<td> Before
<td> After
<tr>
<td><img  src="https://user-images.githubusercontent.com/11772084/222092170-e92dee0a-7613-4fe5-b732-6bf18b270774.png">
<td> <img  src="https://user-images.githubusercontent.com/11772084/222092420-3d1d9933-bef1-4ccb-bee5-cf8e5ec35153.png">
</table>
> fix: Update rating private const and Surfer90 color palette

- spark/src/main/kotlin/com/adevinta/spark/components/appbar/TopAppBarState.kt
- spark/src/main/kotlin/com/adevinta/spark/components/badge/Badge.kt
- spark/src/main/kotlin/com/adevinta/spark/components/card/Card.kt
- spark/src/main/kotlin/com/adevinta/spark/components/card/ElevatedCard.kt
- spark/src/main/kotlin/com/adevinta/spark/components/drawer/DismissibleDrawerSheet.kt
- spark/src/main/kotlin/com/adevinta/spark/components/drawer/DismissibleNavigationDrawer.kt
- spark/src/main/kotlin/com/adevinta/spark/components/drawer/ModalDrawerSheet.kt
- spark/src/main/kotlin/com/adevinta/spark/components/drawer/ModalNavigationDrawer.kt
- spark/src/main/kotlin/com/adevinta/spark/components/textfields/SelectTextField.kt
Remove ` - ` in doc param as it breaks doc rendering
With the ` - ` it would render like this in AS:
whereas we want it ot look like this:
> fix: Remove `  - ` in doc param as it breaks doc rendering

- .github/workflows/ci.yml
- .github/workflows/dokka.yml
- build-logic/src/main/kotlin/com/adevinta/spark/SparkDokkaPlugin.kt
- build.gradle.kts
Enable Dokka multi-modules feature.
https://kotlin.github.io/dokka/1.8.10/developer_guide/architecture/extension_points/core_extensions/#generation
It will allow us to document multiple modules into a single docs site.
- Dokka website will be generated and archived on each PR.
- Dokka website will not be published when pushing on main, but instead, it will be a manual workflow trigger to avoid publishing -SNAPSHOTS (non-final) docs.
> docs: enable Dokka multi modules

- .github/workflows/ci.yml
As it breaks expected checks to be executed.
Also, modifing md files need to re-build and validate dokka which is part of this workflow.
> ci: remove `paths-ignore` on md and docs files

- spark/src/main/kotlin/com/adevinta/spark/components/tags/Tag.kt
- spark/src/main/kotlin/com/adevinta/spark/components/tags/TagTonal.kt
Change `TonalTag` visibility from internal to public with the `TagDefault.tonalColor()`
This Api is used by a consumer so we still need to let it open until we refine the TonalTag api to allow more states
Related to #215
> refactor: Change TonalTag visibility from internal to public

- spark/src/main/kotlin/com/adevinta/spark/res/AnnotatedStringResource.kt
Add Support for quantity on `annotatedString`
As we go on the Compose migration some screens compatible with i18n that have a styled formatting need to also have acces to this api.
Related to #215 
And we might want to add the same for `stringArrayResource()` as well 🤔
> feat: Add Support for quantity on `annotatedString`

- spark-icons/src/main/kotlin/com/adevinta/spark/icons/SparkIcon.kt
- spark/src/main/kotlin/com/adevinta/spark/components/toggles/Switch.kt
CloseFull icon should be a part of Arrows icon
> fix: Move Close Icon from Account to Arrows

- spark/lint.xml
- spark/src/main/kotlin/com/adevinta/spark/SparkTheme.kt
Add new param to `SparkTheme` & new CompositionLocal `LocalLegacyStyle`
Since we're migrating screens with Spark on the Adevinta Platform we don't want a screen to have a component with different UI if a part of the screen is not yet migrated.
This 'll allow us to have component with a UI close enough from the previous one to avoid huge difference between components .
> feat: Add Legacy option to use previous DS style

- build-logic/src/main/kotlin/com/adevinta/spark/ProjectExtensions.kt
- gradle/libs.versions.toml
Now that we have a stable 8.x version.
> chore: downgrade AGP to stable 8.0.0

- spark-screenshot-testing/src/test/kotlin/com/adevinta/spark/PreviewScreenshotTests.kt
- spark/src/main/kotlin/com/adevinta/spark/components/appbar/BottomAppBar.kt
- spark/src/main/kotlin/com/adevinta/spark/components/buttons/Button.kt
- spark/src/main/kotlin/com/adevinta/spark/components/buttons/FloatingActionButton.kt
- spark/src/main/kotlin/com/adevinta/spark/components/chips/AssistChip.kt
- spark/src/main/kotlin/com/adevinta/spark/components/chips/FilterChip.kt
- spark/src/main/kotlin/com/adevinta/spark/components/chips/InputChip.kt
- spark/src/main/kotlin/com/adevinta/spark/components/chips/SuggestionChip.kt
- spark/src/main/kotlin/com/adevinta/spark/components/icons/IconButton.kt
- spark/src/main/kotlin/com/adevinta/spark/components/icons/IconToggleButton.kt
- spark/src/main/kotlin/com/adevinta/spark/components/menu/DropdownMenu.kt
- spark/src/main/kotlin/com/adevinta/spark/components/rating/RatingLong.kt
- spark/src/main/kotlin/com/adevinta/spark/components/rating/RatingSmall.kt
- spark/src/main/kotlin/com/adevinta/spark/components/rating/RatingStar.kt
- spark/src/main/kotlin/com/adevinta/spark/components/scaffold/Scaffold.kt
- spark/src/main/kotlin/com/adevinta/spark/components/tags/TagFilled.kt
- spark/src/main/kotlin/com/adevinta/spark/components/toggles/CheckBox.kt
- spark/src/main/kotlin/com/adevinta/spark/components/toggles/RadioButton.kt
- spark/src/main/kotlin/com/adevinta/spark/components/toggles/Switch.kt
- spark/src/main/kotlin/com/adevinta/spark/tools/preview/SparkPreviewProvider.kt
- Add legacy button outline.
- Add legacy support for `SparkPreviewParam`.
- Add deprecated `TagFilled` to support previous usages of `TagFilled` with `@Ignore("InternalSparkApi")`
I realized that these changes were missing to either test easily the integration or would make breaking changes if not introduced.
related to #328
> fix: Add fixes for finalizing the v0.1.0

- spark-icons/src/main/kotlin/com/adevinta/spark/icons/SparkIcon.kt
Change SparkIcons from sealed class to interface
I was planning to do it but not this early but [KTIJ-19005](https://youtrack.jetbrains.com/issue/KTIJ-19005) forced our hand
> refactor: Change SparkIcons from sealed class to interface

- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_icon_icon_dark.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_icon_icon_light.png
- spark/src/main/kotlin/com/adevinta/spark/components/badge/Badge.md
- spark/src/main/kotlin/com/adevinta/spark/components/icons/Icon.md
- spark/src/main/kotlin/com/adevinta/spark/components/icons/IconDefaults.kt
- spark/src/main/kotlin/com/adevinta/spark/components/icons/IconTints.kt
- spark/src/main/kotlin/com/adevinta/spark/components/icons/Icons.kt
- Update Icons component to respect Spark specs (with preset sizes and tints).
Generated by paparazzi in this PR files
close #344
> feat: Adapt Icon to respect Spark specs

- .github/actions/paparazzi-golden-images/action.yml
- .github/actions/paparazzi-report/action.yml
- .github/workflows/chat-bot-commands.yml
Enable new chat-bot automations with trigger comments.
- `@spark-ui-bot paparazzi golden images` will run `gradlew recordPaparazziRelease` and commit any update if necessary.
> ci: add support for automated paparazzi update

- .github/workflows/ci.yml
- build-logic/build.gradle.kts
- build-logic/src/main/kotlin/com/adevinta/spark/SparkAndroidPlugin.kt
- build-logic/src/main/kotlin/com/adevinta/spark/SparkProperties.kt
- build-logic/src/main/kotlin/com/adevinta/spark/SparkRootPlugin.kt
- build-logic/src/main/kotlin/com/adevinta/spark/SparkUnitTests.kt
- build-logic/src/main/kotlin/com/adevinta/spark/SparkUtils.kt
- spark-lint/src/test/kotlin/com/adevinta/spark/lint/MaterialComposableUsageDetectorTest.kt
- `globalCiUnitTest` on the root project to execute all `ciUnitTest`
- `ciUnitTest` on each sub project to run unittest
- `spark.ci-unit-test.variant` Gradle property to configure which variant to execute tests on (for Android only), defaults to `release`.
Running `testReleaseUnitTest` would not execute unit tests for JVM modules.
> feat: create global unittest tasks for CI

- build-logic/build.gradle.kts
- build-logic/src/main/kotlin/com/adevinta/spark/ProjectExtensions.kt
- build-logic/src/main/kotlin/com/adevinta/spark/SparkAndroidApplicationPlugin.kt
- build-logic/src/main/kotlin/com/adevinta/spark/SparkAndroidComposePlugin.kt
- build-logic/src/main/kotlin/com/adevinta/spark/SparkAndroidLibraryPlugin.kt
- build-logic/src/main/kotlin/com/adevinta/spark/SparkAndroidLintPlugin.kt
- build-logic/src/main/kotlin/com/adevinta/spark/SparkAndroidPlugin.kt
- build-logic/src/main/kotlin/com/adevinta/spark/SparkKotlinJvmPlugin.kt
And remove JDK 17 toolchain enforcement.
This would force consumers to upgrade their own targets:
```
Cannot inline bytecode built with JVM target 17 into bytecode that is being built with JVM target 11. Please specify proper '-jvm-target' option
```
> fix: downgrade JVM targets and compatibility modes to 11

- spark-icons/src/main/kotlin/com/adevinta/spark/icons/SparkIcon.kt
| CategoriesClothesOutline | Clothes |
|---|---|
| <img src="https://raw.githubusercontent.com/adevinta/spark-tokens/538143e5165ea42bf946b4cbbd2391620d74ae96/assets/spark/icons/CategoriesClothesOutline.svg">  |  <img src="https://raw.githubusercontent.com/adevinta/spark-tokens/538143e5165ea42bf946b4cbbd2391620d74ae96/assets/spark/icons/Clothes.svg"> |
> fix: wrong icon replacement

- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_appbar_topappbar_dark.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_appbar_topappbar_light.png
- spark/src/main/kotlin/com/adevinta/spark/components/appbar/TopAppBar.kt
- spark/src/main/kotlin/com/adevinta/spark/components/navigation/UpNavigationIcon.kt
📋 Changes description
The Up navigation icon got shrinked since the icons got updated for v0.2.0.
✅ Checklist
Introduced with new Icons from 0.2.0 milestone
Related to Remove Small size for button  #453
I have reviewed the submitted code.
I have tested on a phone device/emulator.
📸 Screenshots
Done after adding a preview
> fix: Update UpNavigationIcon size to small

- spark-icons/src/main/kotlin/com/adevinta/spark/icons/SparkIcon.kt
As Spark Icon tokens changed, deprecation message needed to be updated
> fix: Update Icon deprecation message

- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_badge_badgedbox_dark.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_badge_badgedbox_light.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_badge_badgedboxnostroke_dark.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_badge_badgedboxnostroke_light.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_badge_badgedboxwithstroke_dark.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_badge_badgedboxwithstroke_light.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_badge_badgenostroke_dark.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_badge_badgenostroke_light.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_badge_badgewithstroke_dark.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_badge_badgewithstroke_light.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_images_illustration_dark.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_images_illustration_light.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_navigationdraweritem_navigationdraweritem_dark.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_textfields_multilinetextfield_dark.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_textfields_multilinetextfield_light.png
- spark/src/main/kotlin/com/adevinta/spark/components/badge/Badge.kt
- spark/src/main/kotlin/com/adevinta/spark/components/badge/Badge.md
- spark/src/main/kotlin/com/adevinta/spark/components/badge/BadgeIntent.kt
- spark/src/main/kotlin/com/adevinta/spark/components/badge/BadgedBox.kt
- spark/src/main/kotlin/com/adevinta/spark/components/chips/ChipIntent.kt
Update `Badge`component in order to support all intent colors
The fist version of badge had only two intents : Info and Danger. 
Present in the current PR
close #467
> feat: Suppport all intent colors of badge

- README.md
Before:
Add the main Spark dependency: [![Maven Central](https://img.shields.io/maven-central/v/com.adevinta.spark/spark?label=%20&color=success)](https://central.sonatype.com/namespace/com.adevinta.spark) [![Sonatype Nexus (Snapshots)](https://img.shields.io/nexus/s/com.adevinta.spark/spark?label=%20&color=lightgrey&server=https%3A%2F%2Fs01.oss.sonatype.org%2F)](https://s01.oss.sonatype.org/content/repositories/snapshots/com/adevinta/spark/spark/)
After:
Add the main Spark dependency: [![Maven Central](https://img.shields.io/maven-central/v/com.adevinta.spark/spark-bom?label=%20&color=success)](https://central.sonatype.com/namespace/com.adevinta.spark) [![Sonatype Nexus (Snapshots)](https://img.shields.io/nexus/s/com.adevinta.spark/spark-bom?label=%20&color=lightgrey&server=https%3A%2F%2F …
> docs: Update badge link to the BoM dependency

- catalog/src/main/kotlin/com/adevinta/spark/catalog/util/Previews.kt
`isPro` param has been removed from color token definition, so it needs to be removed in Catalog App as well.
> fix: Remove isPro param from preview in Catalog App

- spark/src/main/kotlin/com/adevinta/spark/components/tags/Tag.kt
Added a semantic on the Spark Tag to merge the descendant nodes for UI tests.
When UI testing a `TagTinted` component, there was an issue trying to find the text inside of it. Indeed we need to merge the descendants of this composable to access the text inside.
Validated with @soulcramer 
[Contributing](https://github.com/adevinta/spark-android/blob/main/docs/contributing.md) has more information and tips for a great pull request.
> fix: merge descendants of Tag for UI tests

- spark/src/main/kotlin/com/adevinta/spark/components/snackbars/Snackbar.kt
Apply a SparkTheme.shapes.small shape of 8 dp on the Snackbar
- [Closes issue 514](closes issue https://github.com/adevinta/spark-android/issues/514)
> fix(snackbar): apply the SparkTheme.shapes.small shape on snackbars

- catalog/build.gradle.kts
- catalog/src/main/kotlin/com/adevinta/spark/catalog/CatalogApp.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/showkase/CurrentScreen.kt
The Showkase part of CatalogApp loses its state when rotating the screen. This change saves the state across configuration changes.
> fix: Save screen state on config change in CatalogApp

- catalog/src/main/kotlin/com/adevinta/spark/catalog/CatalogApp.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/checkboxes/CheckboxConfigurator.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/examples/samples/checkbox/CheckboxExamples.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/model/Components.kt
- catalog/src/main/res/values/strings.xml
Adds configurable example for 
- checkbox group
- standalone checkbox 
- labeled checkbox in CatalogApp
close #507
> feat: Add configurable example for checkboxes in CatalogApp

- catalog/src/main/kotlin/com/adevinta/spark/catalog/examples/samples/checkbox/CheckboxExamples.kt
Refactor an example of checkbox group in CatalogApp
- Use loop to manage parent and children states.
In the case of a large group of checkboxes, it would be inefficient to create a state for each child checkbox.
> chore: Refactor checkbox group example

- catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/toggles/CheckboxConfigurator.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/toggles/SwitchConfigurator.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/examples/samples/toggles/CheckboxExamples.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/examples/samples/toggles/SwitchExamples.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/model/Components.kt
- catalog/src/main/res/values/strings.xml
Adds configurable example for 
- standalone switch 
- labeled switch in CatalogApp
close #508
> feat: Add configurable example for Switches in CatalogApp

- spark/src/main/kotlin/com/adevinta/spark/components/dialog/ModalFullScreenScaffold.kt
Add spacing to buttons and add a new `reverseButtonOrder` param to, like its name indiquate, reverse the order between the support and main button.
As mentioned [here](https://adevinta.slack.com/archives/C04QQEU3Y2H/p1689755220968659) a spacing was missing between buttons in portrait mode
<table>
<tr>
<td> Before 
<td> After
<tr>
<td> <img src="https://github.com/adevinta/spark-android/assets/11772084/cf7c32d7-0dd1-4bdb-9be1-82ce31549f57"/>
<td> <img src="https://github.com/adevinta/spark-android/assets/11772084/130214f5-a7d8-4859-b18a-8c970f75300a"/>
</table>
Close #546
> fix: ModalFullScreenScaffold has now a spacing between button in portrait and add reverse order

- .github/CODEOWNERS
Add @spark-contributors-android as code owners
When 2 of the current code owners are not availables we have to manually add spark android contributors to PR to make them review it.
This aim to add them by default wdyt @SimonMarquis ?
Note that the @spark-contributors-android consist of senior Polaris developers that have the rights to validate or refuse PR
> chore: add spark-contributors-android as code owners so that they're assigned as reviewers to every PR

- catalog/src/main/res/drawable/ic_launcher_background.xml
- catalog/src/main/res/drawable/ic_launcher_foreground.xml
- catalog/src/main/res/values-night/colors.xml
- catalog/src/main/res/values/colors.xml
Create color references and use them in the adaptive icon foreground & background drawables to change the icon color on the theme mode
I was inspired by [this PR on NowInAndroid](https://github.com/android/nowinandroid/pull/809) as I didn't knew we could change the color of the icon depending on the theme 🤩
> feat: add the ability to change the launcher icon color depending on the theme mode

- spark/src/main/kotlin/com/adevinta/spark/components/dialog/ModalFullScreenScaffold.kt
- Make the content take a weight with fill false to reduce its size priority so that it doesn't push the buttons out of the screen
- Update close icon color to `onSurface.dim2` and add content description for a11y
- Allow passing `illustrationContentScale` to handle content scale of the illustration (the default is `ContentScale.Fit`)
- Add surface to the buttons and update padding so that it is spaced with the content
- Add padding for dialog window to avoid it touching the screen edges
close #599
> fix: content was not adapting to button spaces when too big

- catalog/src/main/kotlin/com/adevinta/spark/catalog/util/Url.kt
Most of them are used inside String templating, and would introduce unexpected double slashes that could break the url.
For example:
- ✅ https://adevinta.github.io/spark-android/spark/com.adevinta.spark.components.appbar/index.html
- ❌ https://adevinta.github.io/spark-android/spark//com.adevinta.spark.components.appbar/index.html
> fix: remove trailing slash from `Url`s

- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_buttons_buttoncontrastintents_dark.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_buttons_buttoncontrastintents_light.png
- spark/src/main/kotlin/com/adevinta/spark/components/buttons/ButtonContrast.kt
ButtonIntent.Surface is an exception in case of ButtonContrast. As the contaner color is surface, the content color should not be `intent.colors.color()` but rather `onColor``
Present in the current PR
close #611
> fix: Update content color for ButtonIntent.Surface for ButtonContrast

- catalog/src/main/kotlin/com/adevinta/spark/catalog/CatalogApp.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/themes/Theme.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/themes/themeprovider/adevinta/AdevintaTheme.kt
> fix: Rename all refs from Polaris to Adevinta in CatalogApp

- CHANGELOG.md
- gradle.properties
This reverts commit 1d1bb899
I've done goofed on the release 0.4.0 by setting the release version to `0.5.0-SNAPSHOT` instead of `0.4.0`
> Revert: "chore: prepare version 0.4.0 (#621)"

- catalog/src/main/kotlin/com/adevinta/spark/catalog/CatalogApp.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/icons/IconDemoScreen.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/icons/IconExampleScreen.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/icons/IconsScreen.kt
- catalog/src/main/res/values/strings.xml
Add new tab to CatalogApp to display all available `SparkIcons`. It also includes examples of usages of selected icon inside :  
- Button
- Icon Button
- Tag
- Chip
- Switch
- Tab
Long click on an icon copy its name to the clipboard.
[Icons Demo.webm](https://github.com/adevinta/spark-android/assets/36896406/37e57b35-5f5b-48d5-8fe2-ecc81d582a49)
close #635
> feat: Add Icons demo to CatalogApp

- catalog/proguard-rules.pro
Proguard will rename resources and remove unused (explicit) resources.
This lead to an empty page of icons in the catalog app.
> fix(catalog): add proguard rules to keep the names of spark icons resources

- spark/src/main/kotlin/com/adevinta/spark/components/textfields/DefaultSparkTextFieldColors.kt
- spark/src/main/kotlin/com/adevinta/spark/components/textfields/SparkTextField.kt
- spark/src/main/kotlin/com/adevinta/spark/components/textfields/SparkTextFieldImpl.kt
Made the `readonly=false` required for the TextfField to look focused 
The textfield was using it's focused style in read only, now it need to not be read only before to have this visual.
https://github.com/adevinta/spark-android/assets/11772084/315145a2-4502-4fd3-8651-0528ae97a0b6
Close #633
> fix: Make the readonly Textfields not take the focus look when focused

- catalog/src/main/kotlin/com/adevinta/spark/catalog/themes/SegmentedButton.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/themes/ThemePicker.kt
Changed color of segmented control from support to accent and made the switch text full width instead of the SwitchLabelled
Since the color token change the segmented button was no longer distinguishable from the main color.
> fix(picker): Modify Segmented color to be more visible and make switch take full width

- catalog/src/main/kotlin/com/adevinta/spark/catalog/icons/IconsScreen.kt
| Before | After |
|---|---|
| ![2023-08-24-13 41 10](https://github.com/adevinta/spark-android/assets/1921278/8e8714ee-a1e3-42e4-b253-b31edb5c4803) | ![2023-08-24-13 42 22](https://github.com/adevinta/spark-android/assets/1921278/f64793c6-9269-4c25-814c-e50469876c0b) |
> fix: update catalog app to show `ExtraLarge` icons

- catalog/src/main/kotlin/com/adevinta/spark/catalog/examples/samples/toggles/CheckboxExamples.kt
- catalog/src/main/res/values/strings.xml
- fix wording
- simplify checkbox example by removing intents as this part is covered by configurator
> fix: minor fixes in CatalogApp

- .github/dependabot.yaml
Since we have enabled grouped updates, it's now easier to reach the default threshold of 5 open PRs for dependabot.
And at the moment, dependabot has reached this limit and won't open any more PRs: https://github.com/adevinta/spark-android/network/updates/716645372
> chore: Increase the default number of max open PRs for dependabot

- .github/CODEOWNERS
Remove marina from the code owner file to avoid sending a ping on every PR
Since Marina is no longer a member of the org she shouldn't be considered a code owner anymore
> chore: Remove Marina as code owner

- spark/src/main/kotlin/com/adevinta/spark/components/dialog/ModalFullScreenScaffold.kt
Content gets overlapped by TopAppBar in ModalFullScreenScaffold component when we set the illustration to null.
This fix is required whenever we're using ModalFullScreenScaffold component with no illustration in order to have a proper top padding between the TopAppBar and the content. This fix handles "PhonePortrait" form factor only.
We can easily reproduce the issue using ModalFullScreenScaffold component preview itself. If we set the illustration to "null", the Text content is overlapped by the TopAppBar.
[Contributing](https://github.com/adevinta/spark-android/blob/main/docs/contributing.md) has more information and tips for a great pull request.
> fix: ModalFullScreenScaffold top padding issue when no illustration

- spark/src/main/kotlin/com/adevinta/spark/SparkTheme.kt
- spark/src/main/kotlin/com/adevinta/spark/components/card/Card.kt
- spark/src/main/kotlin/com/adevinta/spark/components/tab/Tab.kt
- spark/src/main/kotlin/com/adevinta/spark/components/tab/TabRow.kt
Tabs now have 48dp of min height (same as M3) to ensure that they don't appear squished.
By integrating the snapshot of 0.5.0 it appears that tabs have regressions where they lose their min height
> fix: Make the tabs have a min height 

- build-logic/build.gradle.kts
- build-logic/src/main/kotlin/com/adevinta/spark/ProjectExtensions.kt
- build-logic/src/main/kotlin/com/adevinta/spark/SparkDokkaPlugin.kt
- build-logic/src/main/kotlin/com/adevinta/spark/SparkUnitTests.kt
- With eager APIs: https://scans.gradle.com/s/2e4hhzdjjpida/performance/configuration#summary-tasks-created-during-configuration
Created during configuration: 82
- With configuration avoidance APIs: https://scans.gradle.com/s/diht3rnwwokbk/performance/configuration#summary-tasks-created-during-configuration
Created during configuration: 18
> fix(gradle): Migrate to configuration avoidance APIs

- spark/src/main/kotlin/com/adevinta/spark/components/surface/Surface.kt
Use elevation instead of absolute elevation as shadow elevation in `Surface`.
This changed was inspired from #740 
In #702 we updated the `Surface` to use the M2 elevation system instead of the tinted one from M3. During the dev I made the mistake of using the absolute elevation as shadow elevation.
This was fixed but I found out it was only in one of the 4-5 different api for `Surface`. As we use these api for icon buttons every buttons where using the absolute elevation and was more visible on buttons with no background like `GhostButton`
close #726
> fix: Other APi of surface where using the wrong elevation

- .github/workflows/ci.yml
- Updating the concurrency group to include the merge ref.
- Removing the custom analysis path (to be checked later).
> feat(ci): restore support for merge queue behavior

- .github/workflows/pr-icon-updates.yml
- Checkout repository with appropriate token to trigger the CI if updates are committed
- Detect recursive calls based on last commit message
- Fix commit message with properly escaped backticks
> feat: improve `pr-icon-updates` workflow

- .github/workflows/pr-icon-updates.yml
```
The workflow is not valid. .github/workflows/pr-icon-updates.yml (Line: 18, Col: 9): Unrecognized named-value: 'env'. Located at position 37 within expression: github.event.head_commit.message != env.COMMIT_MSG
```
https://github.com/adevinta/spark-android/actions/runs/6403865028
> fix: `env` variable can't be accessed from job conditional

- catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/tabs/TabsConfigurator.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/model/Components.kt
Add a configurator for the tab
Add a configurator for the tab in Catalog app
Fixes [#682](https://github.com/adevinta/spark-android/issues/682)
> feat(catalog): Add a configurator for the tab

- .github/workflows/pr-icon-updates.yml
https://github.com/adevinta/spark-android/actions/runs/6473222749/job/17575468633#step:3:7
```
Run gh pr create --fill
gh: To use GitHub CLI in a GitHub Actions workflow, set the GH_TOKEN environment variable. Example:
env:
GH_TOKEN: ${{ github.token }}
Error: Process completed with exit code 4.
```
> fix: restore GitHub token for CLI command in `pr-icon-updates.yml`

- catalog/src/main/kotlin/com/adevinta/spark/catalog/examples/samples/tabs/TabsExamples.kt
| Before | After |
|---|---|
| ![2023-11-07-12 58 32](https://github.com/adevinta/spark-android/assets/1921278/e9732bad-264c-4fed-b507-0dc3060e44d3) | ![2023-11-07-12 59 13](https://github.com/adevinta/spark-android/assets/1921278/15ce87ba-ada5-4eeb-9f52-11fa18fe001d) |
| ![2023-11-07-12 53 03](https://github.com/adevinta/spark-android/assets/1921278/3477796b-7283-4b46-868d-bb5e8972c935) | ![2023-11-07-12 53 06](https://github.com/adevinta/spark-android/assets/1921278/74dd1417-3303-4d64-920e-530a2d2a1a2d) |
> chore: fix typos in `TabsExamples` and replace one icon to fit the style

- settings.gradle.kts
Finding where/what to add when testing new compose versions is a pain in the a**, adding this repository once for all would streamline future updates.
> feat(maven): add repository for pre-release artifacts of compose-compiler

- README.md
- spark/src/main/kotlin/com/adevinta/spark/components/textfields/SelectTextFields.md
- spark/src/main/kotlin/com/adevinta/spark/tokens/Color.kt
Now that we have a proper domain name, we should use it 🤓
> fix: Replace zeroheight links with spark.adevinta.com

- .editorconfig
- catalog/src/main/kotlin/com/adevinta/spark/catalog/backdrop/Backdrop.kt
- spark/src/main/kotlin/com/adevinta/spark/components/bottomsheet/ModalBottomSheetLayout.kt
- spark/src/main/kotlin/com/adevinta/spark/components/bottomsheet/SheetDefaults.kt
- spark/src/main/kotlin/com/adevinta/spark/components/bottomsheet/Swipeable.kt
- spark/src/main/kotlin/com/adevinta/spark/components/bottomsheet/SwipeableV2.kt
- spark/src/main/kotlin/com/adevinta/spark/components/bottomsheet/modal/ModalBottomSheet.kt
- spark/src/main/kotlin/com/adevinta/spark/components/bottomsheet/scaffold/BottomSheetScaffold.kt
- spark/src/main/kotlin/com/adevinta/spark/components/rating/RatingStar.kt
And re-enable `ktlint_standard_function-naming`
> feat(spotless): enable `ktlint_function_naming_ignore_when_annotated_with=Composable`

- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.iconbutton_IconButtonScreenshot_test_large.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.iconbutton_IconButtonScreenshot_test_medium.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.iconbutton_IconButtonScreenshot_test_small.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.iconbutton_IconToggleButtonScreenshot_test_pill_large.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.iconbutton_IconToggleButtonScreenshot_test_pill_medium.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.iconbutton_IconToggleButtonScreenshot_test_pill_small.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.iconbutton_IconToggleButtonScreenshot_test_rounded_large.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.iconbutton_IconToggleButtonScreenshot_test_rounded_medium.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.iconbutton_IconToggleButtonScreenshot_test_rounded_small.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.iconbutton_IconToggleButtonScreenshot_test_square_large.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.iconbutton_IconToggleButtonScreenshot_test_square_medium.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.iconbutton_IconToggleButtonScreenshot_test_square_small.png
- spark/src/main/kotlin/com/adevinta/spark/components/iconbuttons/IconButtonIntent.kt
IconButton and IconToggleButton were missing the info intent color
I think this was because this intent was added later to the button intents
Close #706
> fix: Add Info as Icon buttons intent color

- spark/src/main/kotlin/com/adevinta/spark/components/iconbuttons/IconButton.kt
- spark/src/main/kotlin/com/adevinta/spark/components/iconbuttons/toggle/IconToggleButton.kt
The Tooltip Box seems to not apply the constraint so I had to wrap all of it inside a Box.
Close #773 
It now behaves like a Material `IconButton`
> fix: Fix ConstraintLayout Constraint not being applied to IconButtons  & IconToggleButton

- .github/workflows/dependabot-dependency-guard.yml
Adds a new automated workflow to run `dependencyGuardBaseline` Gradle task whenever a new PR updates a Gradle dependency.
This _should_ automatically makes PRs merge-able without needing to manually update the dependencies files.
> feat(dependabot): add DependencyGuard baseline on PRs

- gradle/wrapper/gradle-wrapper.properties
- gradlew.bat
Update Gradle Wrapper from 8.5 to 8.6.
Read the release notes: https://docs.gradle.org/8.6/release-notes.html
---
- Gradle release: `8.6`
- Distribution (-bin) zip checksum: `9631d53cf3e74bfa726893aee1f8994fee4e060c401335946dba2156f440f24c`
- Wrapper JAR Checksum: `d3b261c2820e9e3d8d639ed084900f11f4a86050a8f83342ade7b6bc9b0d2bdd`
---
<details>
<br /> …
> chore(deps): bump Gradle Wrapper from 8.5 to 8.6

- catalog/src/main/kotlin/com/adevinta/spark/catalog/examples/example/ExampleItem.kt
| Before | After |
|---|---|
| ![2024-02-14-15 32 39](https://github.com/adevinta/spark-android/assets/1921278/4b658857-9e37-4918-923e-e59d0dd913f1) | ![2024-02-14-15 34 29](https://github.com/adevinta/spark-android/assets/1921278/788aaff7-d78f-490e-b24b-100839c9e8bc) |
> chore(catalog): remove non-clickable icon on example Cards

- catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/text/TextLinkConfigurator.kt
- catalog/src/main/res/values/strings.xml
- spark/src/main/kotlin/com/adevinta/spark/components/text/TextLink.kt
Fixes QA comments by @elisa-hery 
https://github.com/adevinta/spark-android/issues/775#issuecomment-1916567106
- according to the specs, default color is basic. I think it should be default color on catalog app as well, for consistancy (at the moment it's main).
> fix: Fix for TextLink QA Comments

- spark/src/main/kotlin/com/adevinta/spark/components/progress/tracker/ProgressTracker.kt
Previously the tracks were enabled only if the steps it's associated to
was also enabled.
Now it'll also check if the next is enabled
This is not yet listed in the specs but if the a step is disabled then the start and end tracks have to be disabled also
Related to #780
> fix(progresstracker): Correct the tracks enabled state

- spark/src/main/kotlin/com/adevinta/spark/components/buttons/Button.kt
We use the weight modifier to force the content to take only the space it has available instead of pushing the other contents
Closes #916  
<table>
<tr>
<th>Old</th>
<th>New</th>
</tr>
<tr>
<td><img width="242" alt="image" src="https://github.com/adevinta/spark-android/assets/11772084/f85b4df8-8e89-4295-b526-3df51a842331"></td>
<td><img width="242" alt="image" src="https://github.com/adevinta/spark-android/assets/11772084/4d9e2f75-861f-42d8-b559-ac357a5d4a3d">
</td>
</tr>
</table>
> fix: Fix the button end icon being squished when content is too long

- catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/slider/SliderConfigurator.kt
Fix Slider configurator vertical scroll crash
After merging vertical layout PR #975 
it doen't allow nested scroll
So this caused a crash on Slider configurator,
now it's fixed
> fix: Fix Slider configurator vertical scroll crash

- build-logic/build.gradle.kts
- build-logic/src/main/kotlin/com/adevinta/spark/SparkProperties.kt
- build-logic/src/main/kotlin/com/adevinta/spark/SparkSpotlessPlugin.kt
- gradle/libs.versions.toml
We used to rely on spotless's default ktlint version (`KtLintStep.defaultVersion()`).  
This will enable us to update versions independently.  
As a first step, the default version `1.0.1` will be used (`1.2.1` being the current latest version).  
`ktlint-bom` is referenced in `libs.versions.toml` to make dependabot aware of it.
This should unlock #911
> feat: decorrelate spotless and ktlint

- spark/build.gradle.kts
Expose kotlinx.collections.immutable dependency as it is needed for TextLink component
This PR intends to solve the error `Cannot access class 'kotlinx.collections.immutable.ImmutableMap'. Check your module classpath for missing or conflicting dependencies` when a `TextLink` is used in a Gradle module that does not include the `org.jetbrains.kotlinx:kotlinx-collections-immutable` dependency.
Closes #1031
Does not apply.
> fix(deps): Fix for #1031 - Update build.gradle.kts

- CHANGELOG.md
- catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/popover/PopoverConfigurator.kt
The popover configurator  was present and updated correctly but it was not applied on the actual popover.
Close #986
> fix(Popover): The intent was not applied in the configurator

- .github/actions/setup-gradle/action.yml
`validate-wrappers: true` has been recently added to `gradle/actions/setup-gradle`
> chore: merge Gradle setup and Wrapper validation steps

- spark/src/main/kotlin/com/adevinta/spark/components/image/Image.kt
resolves adevinta/spark-android#1061
adevinta/spark-android#1061
As mentioned in the linked issue, I just added the errorIcon and emptyIcon fun args to the public Image fun.
If you desire to have a custom error placeholder instead of the default error image or if you want to easily be able to have the same placeholder for both, this is necessary.
Closes #1061
> feat: Add `emptyIcon` and `errorIcon` parameters with default values to `Image` Composable

- docs/CONTRIBUTING.md
Code formatting is one of the first steps in the CI, even before attempting to build the code.
It makes more sense to move it first in the list, as it will always fail the PR in case of formatting issue.
> chore(contributing): move code formatting tasks first in the list

- spark/src/main/kotlin/com/adevinta/spark/components/bottomsheet/scaffold/BottomSheetScaffold.kt
Add sheetPeekHeight as it's required by consumers,
It used to exist in old versions of BottomSheet,
After the addition of the new BottomSheet Component we have not exposed this parameter.
So now we are making it available again
> feat(BottomSheet): Add sheetPeekHeight to BottomSheetScaffold

- .github/actions/paparazzi-golden-images/action.yml
This will force cleaning unused golden images.
> feat(paparazzi): migrate from `recordPaparazziRelease` to `cleanRecordPaparazziRelease`

- gradle/wrapper/gradle-wrapper.properties
- gradlew
Update Gradle Wrapper from 8.7 to 8.8.
Read the release notes: https://docs.gradle.org/8.8/release-notes.html
---
- Gradle release: `8.8`
- Distribution (-bin) zip checksum: `a4b4158601f8636cdeeab09bd76afb640030bb5b144aafe261a5e8af027dc612`
- Wrapper JAR Checksum: `cb0da6751c2b753a16ac168bb354870ebb1e162e9083f116729cec9c781156b8`
---
<details>
<br /> …
> chore(deps): Update Gradle Wrapper from 8.7 to 8.8

- catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/textfields/ComboBoxConfigurator.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/textfields/DropdownsConfigurator.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/model/Components.kt
- catalog/src/main/res/values/strings.xml
- spark/src/main/kotlin/com/adevinta/spark/components/bottomsheet/BottomSheet.kt
Add configurators that use the current impl of both Dropdown and ComboBox to serve as base for the impl of new Spark Specs
Closes #1138
> feat(dropdown): Add configurators for Dropdown and Combobox

- CHANGELOG.md
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_images_useravatar_dark.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_images_useravatar_light.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_menu_dropdownmenu_dark.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_menu_dropdownmenu_light.png
- spark/src/main/kotlin/com/adevinta/spark/components/image/UserAvatar.kt
Refactor the indicator to position it at the new right place and use an `Icon` instead of an `Illustration` to display the empty image to make it tinted now.
Closes #1128
> fix: Make UserAvatar compatible with dark mode

- catalog/src/main/kotlin/com/adevinta/spark/catalog/examples/samples/dialog/ModalExamples.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/examples/samples/dialog/modal/ModalSample.kt
- spark/src/main/kotlin/com/adevinta/spark/components/dialog/ModalScaffold.kt
- spark/src/main/res/values-de/strings.xml
- spark/src/main/res/values-fr/strings.xml
- spark/src/main/res/values/strings.xml
Hide the Bottom App Bar in the Modal when no actions are provided and in the Dialog layout I've also added the Close action so we still have a clear way to indicate that the Dialog can be closed with an action.
A new example screen as been added for testing.
I didn't expect from the specs that the Modal could have no actions. This is now clarified so we need to hide the Bottom App Bar when no actions are provided.
Closes #1168
@adevinta/spark-design 
I've added a private api to be able to combine 2 `PaddingValues` between each others and we may want to publish it in the future if it's not planned by Google 🤔
> fix(modal): Allow ModalScaffold to take no buttons

- spark/src/main/kotlin/com/adevinta/spark/components/snackbars/Snackbar.kt
QA reported Snackbar was not showing,
actually it was showing but immediately gets disappeared, due to action dismiss gets called.
I removed this line.
now works well
> fix: Snackbar not showing

- catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/snackbar/SnackbarrConfigurator.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/examples/samples/snackbar/SnackbarExamples.kt
- spark-screenshot-testing/src/test/kotlin/com/adevinta/spark/snackbar/SnackbarDocScreenshot.kt
- spark-screenshot-testing/src/test/kotlin/com/adevinta/spark/snackbar/SnackbarScreenshot.kt
- spark-screenshot-testing/src/test/kotlin/com/adevinta/spark/snackbar/TestData.kt
- spark/src/main/kotlin/com/adevinta/spark/components/snackbars/Snackbar.kt
- spark/src/main/kotlin/com/adevinta/spark/components/snackbars/Snackbar.md
- spark/src/main/kotlin/com/adevinta/spark/components/snackbars/SnackbarColors.kt
- spark/src/main/kotlin/com/adevinta/spark/components/snackbars/SnackbarDefault.kt
- spark/src/main/kotlin/com/adevinta/spark/components/snackbars/SnackbarError.kt
- spark/src/main/kotlin/com/adevinta/spark/components/snackbars/SnackbarHost.kt
- spark/src/main/kotlin/com/adevinta/spark/components/snackbars/SnackbarValid.kt
Add previously remove api and add an Error deprecation on them with a `ReplaceWith` to ease migration.
Removal of these apis made upgrading from Spark 0.10.1 to 0.11.0 a nightmare as no instruction was available in the code to replace them.
> fix(release): Provide Replace fixes for Snackbar breaking changes

- catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/textfields/TextFieldsConfigurator.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/examples/samples/textfields/TextfieldsExamples.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/model/Components.kt
- spark-screenshot-testing/src/test/kotlin/com/adevinta/spark/textfields/TextFieldScreenshot.kt
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.textfields_MultilineTextFieldScreenshot_bigValue.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.textfields_MultilineTextFieldScreenshot_showcase__dark.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.textfields_MultilineTextFieldScreenshot_showcase__light.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.textfields_MultilineTextFieldScreenshot_smallValue.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.textfields_TextFieldDocScreenshot_multilineTextFieldShowcase__dark.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.textfields_TextFieldDocScreenshot_multilineTextFieldShowcase__light.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.textfields_TextFieldDocScreenshot_selectTextFieldShowcase__dark.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.textfields_TextFieldDocScreenshot_selectTextFieldShowcase__light.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.textfields_TextFieldDocScreenshot_textFieldShowcase__dark.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.textfields_TextFieldDocScreenshot_textFieldShowcase__light.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.textfields_TextFieldScreenshot_bigValue.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.textfields_TextFieldScreenshot_disabled.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.textfields_TextFieldScreenshot_enabled.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.textfields_TextFieldScreenshot_smallValue.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_textfields_textfieldslots.png
- spark/src/main/kotlin/com/adevinta/spark/components/textfields/SparkTextFieldImpl.kt
- spark/src/main/kotlin/com/adevinta/spark/components/textfields/SparkTextFieldMeasurePolicy.kt
I've added a new example page in the catalog app to test that they now are centered and I've replaced the Icon addon used in the screenshot test by the
The wrong padding was applied to the TextField label and when aligning vertically the Addons we used the same function for the Palceholdera nd the Label but this doesn't  work for the Addons, we should only center them without relying on their height.
Close #1243
> fix(TextField): Revert change that made addons not centered

- catalog/src/main/kotlin/com/adevinta/spark/catalog/CatalogApp.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/buttons/ButtonsConfigurator.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/buttons/IconButtonsConfigurator.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/buttons/IconToggleButtonsConfigurator.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/chips/ChipsConfigurator.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/divider/DivivderConfigurator.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/popover/PopoverConfigurator.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/progressbar/ProgressbarConfigurator.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/progresstracker/ProgressTrackerConfigurator.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/rating/RatingConfigurator.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/slider/SliderConfigurator.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/snackbar/SnackbarConfigurator.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/tabs/TabsConfigurator.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/tags/TagsConfigurator.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/text/TextLinkConfigurator.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/textfields/ComboBoxConfigurator.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/textfields/DropdownsConfigurator.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/textfields/TextFieldsConfigurator.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/toggles/CheckboxConfigurator.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/toggles/RadioButtonConfigurator.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/toggles/SwitchConfigurator.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/examples/samples/popover/PopoverExamples.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/themes/ThemePicker.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/ui/ButtonGroup.kt
- spark/src/main/kotlin/com/adevinta/spark/components/popover/Popover.kt
- spark/src/main/kotlin/com/adevinta/spark/components/tags/Tag.kt
Add a ButtonGroup component that encapsulate a `Text` that serve as a label and a `SegmentedButton`
We use the same pattern when using the Segmented button which is show a label and the `SegmentedButton`.
We also 95% of the time list enum values in it so the `ButtonGroup` can work with them to automatically list them.
> refactor(catalog): Extract ButtonGroup composable for reusability and simplify it.

- spark/src/main/kotlin/com/adevinta/spark/components/dialog/ModalScaffold.kt
When the width of buttons is too big then they will stack each others but no padding was set for this case
close [SPA-15](https://jira.ets.mpi-internal.com/browse/SPA-15)
> style: Adjust vertical spacing in ModalScaffoldDialogContent

- gradle/wrapper/gradle-wrapper.properties
chore(deps): bump Gradle Wrapper from 8.10.1 to 8.10.2.
Read the release notes: https://docs.gradle.org/8.10.2/release-notes.html
---
- Gradle release: `8.10.2`
- Distribution (-bin) zip checksum: `31c55713e40233a8303827ceb42ca48a47267a0ad4bab9177123121e71524c26`
---
<details>
<br /> …
> chore(deps): bump Gradle Wrapper from 8.10.1 to 8.10.2

- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark_PreviewScreenshotTests_preview_tests_bottomsheet_bottomsheetscaffold.png
- spark/src/main/kotlin/com/adevinta/spark/tokens/Color.kt
The color for Material tcolor tokens for the new surfaces were using Unspecified which would make them transparent in Dialog for ex.
These colors were added with the version upgrade of Material 3 to 1.3.0
> fix(color): Component tha use material color token would be transaprent

- catalog/src/main/kotlin/com/adevinta/spark/catalog/CatalogApp.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/MainActivity.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/datastore/theme/ThemeProperties.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/datastore/theme/ThemePropertiesHandler.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/themes/Theme.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/themes/ThemePicker.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/ui/shaders/colorblindness/ColorBlindSettings.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/ui/shaders/colorblindness/ColorBlindnessMatrix.kt
Introduces colorblindness settings to themes, including colorblindness type
and severity. This allows us to verify the colorblindness experience
within the app.
Close #595
> feat(themes): Add colorblindness settings to themes

- spark/src/main/kotlin/com/adevinta/spark/res/AnnotatedStringResource.kt
`annotatedStringResource` and `annotatedPluralStringResource` have a special handling of `formatArgs`, and some non-trivial rules associated to it.
This PR adds these rules in the javadoc of these methods and an example of how to use it properly.
> docs: update `annotatedStringResource` javadoc

- spark/src/main/kotlin/com/adevinta/spark/components/text/TextLink.kt
One variant of the `TextLinkButton` used the intent `Danger` instead of `Surface` as its default
>  fix(TextLinkButton): Update intent from Danger to Surface

- spark/src/main/kotlin/com/adevinta/spark/res/AnnotatedStringResource.kt
Re-add `annotatedStringResource` function overloads to ease the integration of the 1.0.0 in LBC
The new function that we're supposed ask a migration that is heavier than anticipated and can be done in a next step.
We will be able to remove them in the version 1.8 of compose with integration of new api on `AnnotatedString`
> fix: Revert annotatedStringResource overloads deletions

- spark/src/main/kotlin/com/adevinta/spark/components/tab/TabGroup.kt
- spark/src/main/kotlin/com/adevinta/spark/components/tab/TabGroupDefaults.kt
We previously used the dp value instead of rounding it to dp which meant that the offset was not correctly positioned.
> fix(Tab): tab indicator offset was not placed correctly

- spark/src/main/kotlin/com/adevinta/spark/components/bottomsheet/BottomSheet.kt
- spark/src/main/kotlin/com/adevinta/spark/components/bottomsheet/scaffold/BottomSheetScaffold.kt
- spark/src/main/kotlin/com/adevinta/spark/components/divider/Divider.kt
- spark/src/main/kotlin/com/adevinta/spark/components/icons/Icons.kt
- spark/src/main/kotlin/com/adevinta/spark/components/menu/DropdownMenu.kt
- spark/src/main/kotlin/com/adevinta/spark/components/popover/Popover.kt
- spark/src/main/kotlin/com/adevinta/spark/components/slider/Slider.kt
- spark/src/main/kotlin/com/adevinta/spark/components/text/TextLink.kt
Adds sparkUsageOverlay modifier to component taht were missing it
Remove it from the icon Component as it makes the QA think that a Icon button is a spark component when it's not
> chore: Ajust sparkUsageOverlay modifier usage in components

- catalog/src/main/kotlin/com/adevinta/spark/catalog/examples/samples/bottomsheet/BottomSheetExamples.kt
- spark/src/main/kotlin/com/adevinta/spark/components/bottomsheet/BottomSheet.kt
This temp parameter make it possible to interact with items on the top of the BS when a big cutout is present. Will be fixed in Material 1.4
> fix(bottomsheet): Add statusBar size on the content padding

- CHANGELOG.md
- catalog/src/main/kotlin/com/adevinta/spark/catalog/CatalogApp.kt
- spark/src/main/kotlin/com/adevinta/spark/tokens/Color.kt
Add best attempt to adapt a Material Theme color scheme to a Spark Theme colors
We have a adapter to convert a Spark Theme colors to Material colors but not the contrary. 
Adding this new one enable us to support the dynamic theming of Material You or the premade themes that support the new contrast specs fro mAndroid 15
> feat: Add a ColorScheme to SparkColors adapter

- spark/src/main/kotlin/com/adevinta/spark/components/image/UserAvatar.kt
Comparring the position we have and the one from the figma file I had to adjust them.
However currently I could only use a Y offset whil we also needed a X offset so I added it to the api
Close [#SPA-183](https://jira.ets.mpi-internal.com/browse/SPA-383)
This fix it temporarly but we need a solution to place the badge dynamicalyy to avoid using a brand new size with offset every time.
To be done in [#SPA-184](https://jira.ets.mpi-internal.com/browse/SPA-384)
> fix: UserAvatr badge position is not correct

- gradle/wrapper/gradle-wrapper.properties
chore(deps): bump Gradle Wrapper from 8.10.2 to 8.11.
Read the release notes: https://docs.gradle.org/8.11/release-notes.html
---
- Gradle release: `8.11`
- Distribution (-bin) zip checksum: `57dafb5c2622c6cc08b993c85b7c06956a2f53536432a30ead46166dbca0f1e9`
---
<details>
<br /> …
> chore(deps): bump Gradle Wrapper from 8.10.2 to 8.11

- gradle/wrapper/gradle-wrapper.properties
chore(deps): bump Gradle Wrapper from 8.11 to 8.11.1.
Read the release notes: https://docs.gradle.org/8.11.1/release-notes.html
---
- Gradle release: `8.11.1`
- Distribution (-bin) zip checksum: `f397b287023acdba1e9f6fc5ea72d22dd63669d59ed4a289a29b1a76eee151c6`
---
<details>
<br /> …
> chore(deps): bump Gradle Wrapper from 8.11 to 8.11.1

- catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/image/ImageConfigurator.kt
- catalog/src/main/res/values/strings.xml
- spark/src/main/kotlin/com/adevinta/spark/components/image/Image.kt
- Add string resource descriptions to image options and content scales. 
- Refactor the `SelectedImage` and `ImageContentScale` enums to include 
descriptions, improving accessibility and user understanding. 
- Update the UI to display these descriptions alongside image names in the 
dropdown menu.
Feedbacks from @elisa shown that the content scale settings was difficult to understand and that the content description could not be tested
> feat: enhance image configurator with descriptions

- catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/image/ImageConfigurator.kt
> fix: Imageborder in configurator was not properly representing the component size

- gradle/wrapper/gradle-wrapper.properties
- gradlew
chore(deps): bump Gradle Wrapper from 8.11.1 to 8.12.
Read the release notes: https://docs.gradle.org/8.12/release-notes.html
---
- Gradle release: `8.12`
- Distribution (-bin) zip checksum: `7a00d51fb93147819aab76024feece20b6b84e420694101f276be952e08bef03`
---
<details>
<br /> …
> chore(deps): bump Gradle Wrapper from 8.11.1 to 8.12

- catalog/build.gradle.kts
- catalog/src/main/kotlin/com/adevinta/spark/catalog/CatalogApp.kt
- gradle/libs.versions.toml
- spark/build.gradle.kts
Docs: https://google.github.io/accompanist/testharness/
> chore: replace deprecated Accompanist Test Harness with official `DeviceConfigurationOverride`

- .github/actions/setup-gradle/action.yml
https://github.com/gradle/actions/blob/main/docs/deprecation-upgrade-guide.md#the-gradle-home-cache-cleanup-input-parameter-has-been-replaced-by-cache-cleanup
> chore(gha): replace deprecated `gradle-home-cache-cleanup`

- .github/actions/setup-gradle/action.yml
Remove explicit values that are also default values.
https://github.com/gradle/actions/blob/main/docs/setup-gradle.md
(fixes `cache-cleanup` not having a proper value after incorrect update in #1424)
> chore(gha): cleanup setup-gradle default values

- gradle/wrapper/gradle-wrapper.properties
chore(deps): bump Gradle Wrapper from 8.12 to 8.12.1.
Read the release notes: https://docs.gradle.org/8.12.1/release-notes.html
---
- Gradle release: `8.12.1`
- Distribution (-bin) zip checksum: `8d97a97984f6cbd2b85fe4c60a743440a347544bf18818048e611f5288d46c94`
---
<details>
<br /> …
> chore(deps): bump Gradle Wrapper from 8.12 to 8.12.1

- spark/src/main/kotlin/com/adevinta/spark/tokens/Type.kt
Remove override of `includeFontPadding` on all spark typografy
`includeFontPadding` override is no longer needed since Compose 1.6
> fix: Remove unecessary includeFontPadding

- catalog/src/main/kotlin/com/adevinta/spark/catalog/ui/DropdownEnum.kt
Add `DropdownEnum` that will allow to select an enum entry out of all entries available with a uniform design 
This enum version of the dropdown make it easy for the configurations of component as we use enums to test various states
> feat: Add Catalog component that accept a Enum

- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.textfields_MultilineTextFieldScreenshot_showcase__dark.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.textfields_MultilineTextFieldScreenshot_showcase__light.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.textfields_MultilineTextFieldScreenshot_showcase_disabled__dark.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.textfields_MultilineTextFieldScreenshot_showcase_disabled__light.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.textfields_TextFieldDocScreenshot_multilineTextFieldShowcase__dark.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.textfields_TextFieldDocScreenshot_multilineTextFieldShowcase__light.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.textfields_TextFieldDocScreenshot_selectTextFieldShowcase__dark.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.textfields_TextFieldDocScreenshot_selectTextFieldShowcase__light.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.textfields_TextFieldDocScreenshot_textFieldShowcase__dark.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.textfields_TextFieldDocScreenshot_textFieldShowcase__light.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.textfields_TextFieldScreenshot_bigValue.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.textfields_TextFieldScreenshot_disabled.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.textfields_TextFieldScreenshot_enabled.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.textfields_TextFieldScreenshot_smallValue.png
- spark/src/main/kotlin/com/adevinta/spark/tools/modifiers/Conditions.kt
Fix the conditional modifier extensions
The conditional modifiers seem to drop previous modifiers in case the condition is not met.
After further investigation, it appears that if the condition is not met, the extension returns Modifier instead of this, hence this issue.
> fix: conditional modifiers not working as expected

- catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/ComponentsScreen.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/Navigation.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/buttons/ButtonsConfigurator.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/examples/ComponentsScreen.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/examples/component/ComponentItem.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/model/Components.kt
Add the ability to use multiple configurators for a component
The previous limit of 1 configurator per component made each configurators more complex each time a component could have mutiple visuals like a simple one and a "complex" one which like the Stepper could include additional labels, helpers
> refactor: allow multiple configurators for a single component

- catalog/src/main/kotlin/com/adevinta/spark/catalog/examples/samples/dialog/modal/ModalSample.kt
- spark/src/main/kotlin/com/adevinta/spark/components/dialog/ModalScaffold.kt
Apply latest and simpler workaround to display a Dialog in fullscreen that support edge-to-edge.
Modal `inEdgeToEdge` is now false by default.
Close [SPA-496](https://jira.ets.mpi-internal.com/browse/SPA-496) 
In a screen that doesn't support Edge-to-edge:
| `inEdgeToEdge`: true | `inEdgeToEdge`: false |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/dd47de4e-0546-442a-a578-8b4648e67b77) | ![image](https://github.com/user-attachments/assets/b6beda2c-ec23-4e2c-9fdb-19b36ed91c8d) |
> refactor(modal): edge-to-edge setup now optin instead of optout

- .github/dependabot.yaml
and remove `replaces-base` to restore the default maven repo.
> chore(dependabot): add explicit Gradle Plugins portal registry

- .github/workflows/firebase-app-distribution.yml
as it should not be necessary to build the catalog app and upload it to Firebase.
> chore: remove lfs checkout for firebase-app-distribution.yml

- CHANGELOG.md
- catalog/src/main/kotlin/com/adevinta/spark/catalog/examples/ComponentsScreen.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/icons/IconsScreen.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/model/Components.kt
- catalog/src/main/res/values-fr/strings.xml
- catalog/src/main/res/values/strings.xml
Add generated translations from english to french for the catalog app ressources.
Add a few new a11y content strings to make the app more navigable with a screen reader.
When testing a11y with a screen reader in Android we would get english text read as french which is not ideal.
> feat(catalog): Add french string res

- spark-screenshot-testing/src/test/kotlin/com/adevinta/spark/components/badge/BadgeScreenshot.kt
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.components.badge_BadgeScreenshot_badge.png
> feat: add screenshot tests for `Badge` composable

- catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/bottomsheet/BottomSheetConfigurator.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/buttons/ButtonsConfigurator.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/buttons/IconButtonsConfigurator.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/buttons/IconToggleButtonsConfigurator.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/popover/PopoverConfigurator.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/progressbar/ProgressbarConfigurator.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/progresstracker/ProgressTrackerConfigurator.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/slider/SliderConfigurator.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/snackbar/SnackbarConfigurator.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/tabs/TabsConfigurator.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/text/TextLinkConfigurator.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/toggles/CheckboxConfigurator.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/toggles/RadioButtonConfigurator.kt
- catalog/src/main/kotlin/com/adevinta/spark/catalog/configurator/samples/toggles/SwitchConfigurator.kt
All Dropdowns that display a selection of enum entries is migrated
This is needed for the incoming `DropdownMenu` refactor as it'll impact all `Dropdowns` used in the catalog app.
Also it makes the UI code less verbose to read
> refactor(Catalog): Use Dropdown Enum everywhere it can be used

- spark-icons/src/main/kotlin/com/adevinta/spark/icons/SparkAnimatedIcons.kt
- spark-icons/src/main/res/drawable/spark_icons_animated_collapse_expand.xml
- spark-screenshot-testing/src/test/kotlin/com/adevinta/spark/icons/AnimatedIconsScreenshot.kt
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.components.badge_BadgeScreenshot_badge.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.textfields_DropdownScreenshot_expanded.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.textfields_TextFieldDocScreenshot_selectTextFieldShowcase__dark.png
- spark-screenshot-testing/src/test/snapshots/images/com.adevinta.spark.textfields_TextFieldDocScreenshot_selectTextFieldShowcase__light.png
- spark-screenshot-testing/src/test/snapshots/videos/com.adevinta.spark.icons_AnimatedIconsScreenshot_collapseExpand_collapseexpand.png
- spark/src/main/kotlin/com/adevinta/spark/components/textfields/Dropdown.kt
Add new animated Icon and use it for Dropdown
Replace the rotating expand / collapse icon by a dedicated animated one for the `Dropdown` and `Combobox` component
> feat(dropdown): add animated collapse/expand icon

- spark-screenshot-testing/src/test/kotlin/com/adevinta/spark/icons/AnimatedIconsScreenshot.kt
- spark-screenshot-testing/src/test/snapshots/videos/com.adevinta.spark.icons_AnimatedIconsScreenshot_collapseExpand.png
The current implementation only showed half of the animation (and not the reverse part).
I also removed the unnecessary delay, and match the exact animation duration.
> feat: show the entire expand/collapse animation in screenshot test

- catalog/src/main/kotlin/com/adevinta/spark/catalog/examples/samples/combobox/ComboboxExample.kt
Add the missing `expanded = true` in all examples
Close [SPA-607](https://jira.ets.mpi-internal.com/browse/SPA-607)
https://github.com/user-attachments/assets/e7b4cb75-00b8-4aaf-8cc5-8d0bbfdd8eb7
> fix(Combobox): An example did not open the dropdown on edit

- spark/src/main/kotlin/com/adevinta/spark/components/menu/DropdownMenu.kt
Changed the check icon position from trailing to leading position and adapted the documention accordingly
Closes [SPA-608](https://jira.ets.mpi-internal.com/browse/SPA-608)
> fix(Combobox): Changed Check icon position from end to start

- spark/src/main/kotlin/com/adevinta/spark/components/image/Image.kt
These changes ensure that the image component has a defined size, which is important for the correct rendering and layout of the image.
Add a new check when the `Image` is layout that ensure it has a defined size
This change is needed to ensure we don't get bad behaviours as mentioned in [here](https://github.com/leboncoin/spark-android/pull/1514#issuecomment-2758702162).
Once it's merged and we can verify that it works we can merge #1514
> feat(image): Ensure image has defined size

- spark/src/main/kotlin/com/adevinta/spark/SparkTheme.kt
- spark/src/main/kotlin/com/adevinta/spark/components/image/Image.kt
- spark/src/main/kotlin/com/adevinta/spark/tools/SparkExceptionHandler.kt
Remove remaining logger naming remains
The mentions to the previous name of `SparkExceptionHandler` was not updated in `SparkTheme` argument, in the `Image` Component and in its documentation.
> fix(ExceptionHandler): Remove remaining logger naming remains

- spark/src/main/kotlin/com/adevinta/spark/components/popover/Popover.kt
- Applied `Modifier.weight` to ensure popover content fills remaining space
The change is required because the close button was being pushed out of view when the popover content was too large. 
Closes #1569
> fix(popover): fix hidden close button

- .github/workflows/publish.yml
- README.md
- RELEASING.md
- build-logic/build.gradle.kts
- build-logic/src/main/kotlin/com/adevinta/spark/SparkPublishingPlugin.kt
- build.gradle.kts
- gradle.properties
- gradle/libs.versions.toml
Changes the GitHub Actions workflow to publish to the Central Portal instead of OSSRH. 
We also use Central publishing through the NMCP library from GradleUp  to stay with a simple publishing logic.
The necessary environment variables have also been updated to use the  Central Portal credentials instead of the OSSRH credentials.
See https://central.sonatype.org/news/20250326_ossrh_sunset/
> feat(publish): Migrate publish from ossrh to Central Portal

- spark/src/main/kotlin/com/adevinta/spark/tokens/Layout.kt
This is a typo from the migration of `WindowSizeClass`
> fix(layout): fix gutter size from 18 to 8 dp

- spark/src/main/kotlin/com/adevinta/spark/components/dialog/ModalScaffold.kt
The `ModalScaffold` was missing a `contentWindowInsets` parameter that made customizing the behavior of the inner `Scaffold` impossible.
Also we detected that the content padding was not applied anymore on the portrait configuration of the `ModalScaffold`
> feat: Add contentWindowInsets parameter to ModalScaffold and fix content padding not used in portrait

- .github/gradle.properties
GHA already has 4 CPUs that can be used.
One worker on each CPU is the default value.
- https://docs.github.com/en/actions/how-tos/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
- https://docs.gradle.org/current/userguide/build_environment.html#gradle_properties_reference
> chore(ci): Remove forced `org.gradle.workers.max` on CI

- .github/workflows/publish.yml
- build-logic/src/main/kotlin/com/adevinta/spark/SparkPublication.kt
- build-logic/src/main/kotlin/com/adevinta/spark/SparkPublishingPlugin.kt
- build-logic/src/main/kotlin/com/adevinta/spark/SparkRootPlugin.kt
Migrate from multiple nmcp publications to a single aggregation nmcp publication.
This should prevent accumulating timeouts on each publication task.
> chore(ci): migrate to single aggregation publication

- build-logic/build.gradle.kts
- build.gradle.kts
- gradle/libs.versions.toml
Add missing plugins that should match the declaration from the root build.gradle.kts file.
And rename `android-gradlePlugin` into short form `agp`.
Removes the need of additional dependencies by using the Gradle Plugin Marker Artifacts.
> chore: rewrite Gradle plugins dependencies in build-logic

- spark/src/main/kotlin/com/adevinta/spark/components/textfields/ComboBox.kt
Expose `trailingContent` parameter for `ComboBox` components.
When using the `ComboBox` component in Leboncoin application, the trailing icon can sometimes be close button.
> feat: expose trailingContent for ComboBox interfaces

- CHANGELOG.md
- spark/src/main/kotlin/com/adevinta/spark/components/dialog/ModalScaffold.kt
Remove FLAG_LAYOUT_NO_LIMITS from ModalScaffold
`NO_LIMITS` make the window from a popup take its full content height as height. This makes the popup overflow from the device screen and makes it unscrollable.
> fix(dialog): remove FLAG_LAYOUT_NO_LIMITS from ModalScaffold to allow scrollable popups

- CHANGELOG.md
- spark/src/main/kotlin/com/adevinta/spark/components/rating/RatingInput.kt
- spark/src/test/kotlin/com/adevinta/spark/components/rating/RatingInputTest.kt
- Adds accessibility slider semantics to RatingInput
- Implements drag gesture and haptic feedback for rating selection
- Adds allowSemantics and testTag parameters for a11y and testing
- Refactors constants to RatingDefaults
- Updates and expands RatingInputTest for a11y and interaction coverage
Close [LBCSPARK-298](https://jira.ets.mpi-internal.com/browse/LBCSPARK-298)
> feat(rating): add a11y slider semantics, drag gesture, haptic feedback, and testTag API
